version: 1.0.{build}

image:
- Visual Studio 2013

build_script:
- cmd: .\build.cmd

notifications:
- provider: Email
  to:
  - this@parthopdas.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
